### ISSUE TITLE
escape % in params.

### ISSUE THREAD

**Issue by skywinder** [Ahmed-Ali/JSONExport#19]
example:
```
{"CHG":"-17.9","CHG%":"-0.16"}
```

**Comment by Ahmed-Ali** [comment]
You can checkout the develop branch for this one.
However, your JSON example will have other issues.
The second key when we remove the % from it, it will have the same property name as the first key. Only one property will remain and the second will be ignored.

**Comment by skywinder** [comment]
Yes, thats why I send you example of json. I think it's better to replace escaped symbols by `_` for example. It helps to prevent nameing collisions

**Comment by Ahmed-Ali** [comment]
Technically, it is very easy to be done. But in terms of usability, JSONExport should do more than basic clean up. I mean in case someone has properties with really weird characters like this, I believe it is better to be solved on his design instead of trying to complicate the auto generated classes which can add more unneeded complexity to understanding the mapping between your JSON object and the generated class.

**Comment by skywinder** [comment]
Yes, it's better to fix backend. Sadly, but it's not always possible. I
just suggest  solution for correct handling such situations.


---
Regards,
Petr Korolev

2015-09-07 13:41 GMT+03:00 Ahmed Ali <notifications@github.com>:
