### ISSUE TITLE
Is it better to use copy than strong when using NSString property?

### ISSUE THREAD

**Issue by terwer** [Ahmed-Ali/JSONExport#21]
I use this tool,but it generates strong for NSString,like ```@property (nonatomic, strong) NSString * conWord;```.
I think is it better using copy for NSString property,like ```@property (nonatomic, copy) NSString * conWord;```

**Comment by Ahmed-Ali** [comment]
What difference will it make?
NSString is immutable, which means none will be able to change it.
And under all cases, strong is the default behaviour, and it have been specified just for better readability and explicitly.
If your case really needs to use copy instead of strong, it is so easy to through the Objective-C JSON files.

**Comment by Ahmed-Ali** [comment]
I can think about a scenario where a copy could be more useful (if the value is an NSMutableString instance), but still it is considered as a heck rather than a best practice.
Which means it is hard to generalize such usage.
