### ISSUE TITLE
32bit or 64bit issue

### ISSUE THREAD

**Issue by pengrun** [Ahmed-Ali/JSONExport#36]
Jsonexport converted into NSInteger,in 32bit out-of-bounds.

**Comment by rocketnik** [comment]
I had this problem with some other tool before. It was a product id that was too big for 32bit. Fortunately the backend developer changed it to String. I don't know, if this is also possible for you.

**Comment by Ahmed-Ali** [comment]
I don't think it is frequent now a days when you build against 32bit architecture. So my suggestion is to manually change the property type to more appropriate type. Because JSON export can not know in advance the architecture where the exported model will be used and it is not practical to use types like Long and Double (or even Int64) types without an obvious need for that.
